version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: lab_pet_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # use default R2DBC URL (no options) — migration creates table in public
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/lab_pet_project
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab_pet_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lab_pet_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_SCHEMAS: delivery
      SPRING_FLYWAY_TABLE: flyway_schema_history_delivery

  report-service:
    build: ./report-service
    container_name: report-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - product-service
      - delivery-service
    environment:
      SPRING_PROFILES_ACTIVE: default
      PRODUCT_SERVICE_URL: http://product-service:8080
      PRODUCT_SERVICE_USERNAME: admin
      PRODUCT_SERVICE_PASSWORD: admin
      DELIVERY_SERVICE_URL: http://delivery-service:8081

volumes:
  postgres_data:
